modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/fishcute/Celestial/issues"
[[mods]]
modId="celestial"
version="${version}"
displayName="Celestial"
displayURL="https://github.com/fishcute/Celestial"
logoFile="icon.png"
authors="fishcute, block36_"
description='''
A Minecraft mod for Fabric and Forge that allows you to customize the sky.
'''

[[dependencies.celestial]]
   modId="forge"
   mandatory=true
   versionRange="[45,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.celestial]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.4,1.20)"
   ordering="NONE"
   side="BOTH"

[[dependencies.celestial]]
   modId="kotlinforforge"
   versionRange="[4.10.0,)"
   mandatory=true
   ordering="BEFORE"